export enum ScreenNames {
  Splash = 'Splash',
  StartScreen = 'StartScreen',
  Login = 'Login',
  Register = 'Register',
  BottomTab = 'BottomTab',
  Hangman = 'Hangman',
  FlappyBird = 'FlappyBird',
  WordPuzzle = 'WordPuzzle',
  Quiz = 'Quiz',
  WordMatching = 'WordMatching',
  WordCompletion = 'WordCompletion',
  WordSorting = 'WordSorting',
  CrossWordPuzzle = 'CrossWordPuzzle',
  Home = 'Home', 
  Vocabulary = 'Vocabulary',
  Profile = 'Profile',
  PlayGround = 'PlayGround',
  A1level= 'A1level',
  A2level= 'A2level',
  B1level= 'B1level',
  B2level= 'B2level',
  C1level= 'C1level',
  C2level= 'C2level',
}
